### ISSUE TITLE
`AttributeError` when using `cyber_record echo` command

### ISSUE THREAD

**Issue by tikrgi620** [daohu527/cyber_record#73]
Hello! I'm using this tool to analyze record file collected from Apollo 7.  I greatly appreciate the contributions your work has made to the field, and I have found it to be instrumental. 

However, I encountered this issue when using the `cyber_record info` command: 
```bash
$ cyber_record info -f 8_2.record.00000 
Traceback (most recent call last):
  File "/home/sun/.local/bin/cyber_record", line 8, in <module>
    sys.exit(main())
  File "/home/sun/.local/lib/python3.8/site-packages/cyber_record/main.py", line 157, in main
    cyber_record_info(args.file)
  File "/home/sun/.local/lib/python3.8/site-packages/cyber_record/main.py", line 38, in cyber_record_info
    record = Record(record_file)
  File "/home/sun/.local/lib/python3.8/site-packages/cyber_record/record.py", line 104, in __init__
    self._open(f, mode, allow_unindexed)
  File "/home/sun/.local/lib/python3.8/site-packages/cyber_record/record.py", line 298, in _open
    if mode == 'r': self._open_read(f)
  File "/home/sun/.local/lib/python3.8/site-packages/cyber_record/record.py", line 320, in _open_read
    self._reader.start_reading()
  File "/home/sun/.local/lib/python3.8/site-packages/cyber_record/reader.py", line 60, in start_reading
    for single_index in index.indexes:
AttributeError: 'NoneType' object has no attribute 'indexes'
```
By the way, I'm using Ubuntu 20.04, and the record file was collected from Apollo 7. Given the record file for reproducing this bug: https://drive.google.com/file/d/1W4es2pmQB0RwAKVCmyrVDQhRO1p31fel/view?usp=sharing

How can I solve this issue? Thank you very much!

**Comment by daohu527** [comment]
Record uses `indexs` to index. If it cannot be found, your record may be damaged.

**Comment by tikrgi620** [comment]
I tried to use the `cyber_record recover` command to recover the record file and encountered the same issue: 
```bash
$ protoc --include_imports --descriptor_set_out=tmp --proto_path=/home/as3r/ADSs/apollo-7 /home/as3r/ADSs/apollo-7/modules/planning/proto/planning.proto
$ cyber_record recover -f 8_2.record.00000 -t /apollo/planning -d tmp -m apollo.planning.ADCTrajectory
WARNING:root:msg_type should be:
WARNING:root:	apollo.planning.EStop
WARNING:root:	apollo.planning.TaskStats
WARNING:root:	apollo.planning.LatencyStats
WARNING:root:	apollo.planning.RSSInfo
WARNING:root:	apollo.planning.ADCTrajectory
Traceback (most recent call last):
  File "/home/as3r/.local/bin/cyber_record", line 8, in <module>
    sys.exit(main())
  File "/home/as3r/.local/lib/python3.8/site-packages/cyber_record/main.py", line 162, in main
    cyber_record_recover(args.file, args.desc_file, args.topic, args.msg_type)
  File "/home/as3r/.local/lib/python3.8/site-packages/cyber_record/main.py", line 123, in cyber_record_recover
    record.recover_index(single_index)
  File "/home/as3r/.local/lib/python3.8/site-packages/cyber_record/record.py", line 210, in recover_index
    for s_index in index.indexes:
AttributeError: 'NoneType' object has no attribute 'indexes'
```

I got the following error info in Apollo's docker: 
```bash
[as3r@in-dev-docker:/apollo/recordings]$ cyber_recorder info 8_2.record.00000 
record_file:    8_2.record.00000
version:        1.0
duration:       0.000000 Seconds
begin_time:     1969-12-31-19:00:00
end_time:       1969-12-31-19:00:00
size:           0 Bytes
is_complete:    false
message_number: 0
channel_number: 0
E1015 12:40:11.809468 11228 record_file_reader.cc:86] [cyber_recorder]Record file is not complete.
E1015 12:40:11.809871 11228 info.cc:94] [cyber_recorder]read index section of the file fail. file: 8_2.record.00000
```

Now I suspect that the process used to record the record file exited abnormally. Thank you!
